services:
    proxy:
        image: proxy
        ports:
            - 8080:8080
            - 8443:8443
        restart: always
 
    web:
        depends_on:
            - proxy
        image: web
        restart: always
